server:
  port: 8088
spring:
  datasource:
    user:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring-boot-demo?useSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      password:
    role:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring-boot-demo-1?useSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      password:

# 日志配置文件
logging:
  config: classpath:log4j2/log4j2.xml

